//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserMaster
    {
        public int Id { get; set; }

        [Display(Name = "First Name:")]
        [Required(ErrorMessage = "First name is Required")]
        public string Firstname { get; set; }

        [Display(Name = "Middle Name:")]
        [Required(ErrorMessage = "Middle name is Required")]
        public string MiddleName { get; set; }

        [Display(Name = "Last Name:")]
        [Required(ErrorMessage = "Laste name is Required")]
        public string Lastname { get; set; }

        [Display(Name = "Gender:")]
        [Required(ErrorMessage = "Gender Required")]
        public bool Gender { get; set; }

        [Display(Name = "Birth Date:")]
        [Required(ErrorMessage = "Birthdate is Required")]
        public System.DateTime Birthdate { get; set; }

        [Display(Name = "Address:")]
        [Required(ErrorMessage = "Address is Required")]
        public string Address { get; set; }

        [Display(Name = "City:")]
        [Required(ErrorMessage = "City is Required")]
        public string City { get; set; }

        [Display(Name = "Email:")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email Id is Required")]
        public string EmailId { get; set; }

        [Display(Name = "Password:")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is Required")]
        public string Password { get; set; }

        [NotMapped()]
        [Display(Name = "Confirm Password:")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Confirm password is Required")]
        [CompareAttribute("Password",ErrorMessage ="The Password and confirm password does not match.")]
        public string ConfirmPassword { get; set; }
    }
}
